version: "2"
services:

    mysqld:
        image: mysql:5.6
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: mysqlrootpassword
            MYSQL_USER: user
            MYSQL_PASSWORD: mysqlpassword
            MYSQL_DATABASE: mydatabase

    redis:
        image: redis:3.2-alpine

    python:
        build: .
        links:
            - mysqld
            - redis
        command: "py.test -sv foo"
